version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskDefinition.json"
        LoadBalancerInfo:
          ContainerName: "web"
          ContainerPort: 4000
